# Generated by Django 5.2.1 on 2026-05-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovement",
            name="is_supply",
            field=models.BooleanField(default=False),
        ),
    ]
