# Generated by Django 5.2.14 on 2026-05-27 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventorymovement_is_supply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorymovement",
            name="supplier",
        ),
    ]
