# Generated by Django 5.2.14 on 2026-05-27 03:41

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_remove_inventorymovement_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymovement",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
