# Generated by Django 5.2.1 on 2026-05-31 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_catalogitem_sku"),
        ("inventory", "0004_alter_inventorymovement_unit_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymovement",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_movements",
                to="catalog.catalogitem",
            ),
        ),
    ]
