# Generated by Django 5.2.14 on 2026-06-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_change_product_cascade_to_protect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorymovement",
            name="reference_sale",
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="origen",
            field=models.CharField(
                blank=True,
                help_text="Código de la venta o compra que originó el movimiento",
                max_length=50,
            ),
        ),
    ]
