# Generated by Django 5.2.1 on 2026-05-24 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_records', to='people.client'),
        ),
    ]
