# Generated by Django 5.2.1 on 2026-05-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_servicerecord_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='tip_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
