# Generated by Django 5.2.1 on 2026-05-26 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_servicerecord_quantity_and_more"),
        ("people", "0002_remove_client_email_remove_client_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerecord",
            name="barber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_records",
                to="people.employee",
            ),
        ),
    ]
