# Generated by Django 5.2.1 on 2026-05-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_alter_servicerecord_barber"),
    ]

    operations = [
        migrations.RenameModel("ServiceRecord", "Sale"),
    ]
