# Generated by Django 5.2.1 on 2026-05-27 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_catalogitem_sku"),
        ("operations", "0004_rename_servicerecord_to_sale"),
        ("people", "0003_alter_employee_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={"verbose_name": "Venta", "verbose_name_plural": "Ventas"},
        ),
        migrations.AlterField(
            model_name="sale",
            name="barber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="people.employee",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="people.client",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="performed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="performed_sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="catalog.catalogitem",
            ),
        ),
    ]
