# Generated by Django 5.2.1 on 2026-05-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0005_alter_sale_options_alter_sale_barber_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="barber",
            new_name="employee",
        ),
        migrations.RenameField(
            model_name="sale",
            old_name="service",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="sale",
            old_name="service_price",
            new_name="product_price",
        ),
    ]
