# Generated by Django 5.2.1 on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0007_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
