# Generated by Django 5.2.14 on 2026-06-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0009_purchase_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="codigo",
            field=models.CharField(blank=True, max_length=50, verbose_name="código"),
        ),
        migrations.AddField(
            model_name="sale",
            name="codigo",
            field=models.CharField(blank=True, max_length=50, verbose_name="código"),
        ),
    ]
