# Generated by Django 5.2.14 on 2026-06-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0011_backfill_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="codigo",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="código"
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="codigo",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="código"
            ),
        ),
    ]
