# Generated by Django 5.2.14 on 2026-06-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_alter_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="correo electrónico"
            ),
        ),
    ]
