# Generated by Django 5.2.1 on 2026-06-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_client_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="day_off",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Lunes"),
                    (1, "Martes"),
                    (2, "Miércoles"),
                    (3, "Jueves"),
                    (4, "Viernes"),
                    (5, "Sábado"),
                    (6, "Domingo"),
                ],
                null=True,
                verbose_name="día de descanso",
            ),
        ),
    ]
