# Generated by Django 5.2.1 on 2026-06-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_add_day_off_to_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="document_id",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                verbose_name="documento / cédula",
            ),
        ),
    ]
