# Generated by Django 5.2.14 on 2026-06-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_company_address_company_logo_company_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="closing_time",
            field=models.TimeField(default="19:00", verbose_name="hora de cierre"),
        ),
        migrations.AddField(
            model_name="company",
            name="opening_time",
            field=models.TimeField(default="09:00", verbose_name="hora de apertura"),
        ),
    ]
