# Generated by Django 5.2.1 on 2026-05-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogitem",
            name="current_stock",
            field=models.IntegerField(default=0),
        ),
    ]
