# Generated by Django 5.2.1 on 2026-05-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_catalogitem_current_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogitem",
            name="sku",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="código"
            ),
        ),
    ]
