# Generated by Django 5.2.14 on 2026-06-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_catalogitem_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogitem",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Solo para servicios. Define el bloque de tiempo en la agenda.",
                null=True,
                verbose_name="duración (minutos)",
            ),
        ),
    ]
