# Generated by Django 5.2.1 on 2026-05-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.SlugField(
                        help_text="Identificador usado en el subdominio. Ej: 'luxor'",
                        max_length=63,
                        unique=True,
                    ),
                ),
                (
                    "db_name",
                    models.CharField(
                        help_text="Nombre de la base de datos PostgreSQL. Ej: 'barber_luxor'",
                        max_length=63,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre comercial de la empresa", max_length=200
                    ),
                ),
                (
                    "nit",
                    models.CharField(
                        blank=True, default="", max_length=30, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Subdominio completo. Ej: luxor.barberia.com",
                        max_length=253,
                        unique=True,
                    ),
                ),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dominio",
                "verbose_name_plural": "Dominios",
            },
        ),
    ]
