# Generated by Django 5.2.1 on 2026-06-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="domain",
            field=models.CharField(
                help_text="Subdominio completo. Ej: luxor.colstyle.com",
                max_length=253,
                unique=True,
            ),
        ),
    ]
