# Generated by Django 5.2.14 on 2026-05-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoleMenuPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("barbero", "Barbero"),
                            ("estilista", "Estilista"),
                        ],
                        max_length=20,
                    ),
                ),
                ("menu_key", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Permiso de menú por rol",
                "verbose_name_plural": "Permisos de menú por rol",
                "unique_together": {("role", "menu_key")},
            },
        ),
    ]
