# Generated by Django 5.2.1 on 2026-05-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleCrudPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("barbero", "Barbero"),
                            ("estilista", "Estilista"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "app_key",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("productos", "Productos"),
                            ("ventas", "Ventas"),
                            ("compras", "Compras"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("registrar", "Registrar"),
                            ("modificar", "Modificar"),
                            ("desactivar", "Desactivar"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso de acción por rol",
                "verbose_name_plural": "Permisos de acción por rol",
                "unique_together": {("role", "app_key", "action")},
            },
        ),
    ]
