# Generated by Django 5.2.1 on 2026-06-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_rolecrudpermission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolecrudpermission",
            name="action",
            field=models.CharField(
                choices=[
                    ("registrar", "Registrar"),
                    ("modificar", "Modificar"),
                    ("desactivar", "Desactivar"),
                    ("ajustar", "Ajustar"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rolecrudpermission",
            name="app_key",
            field=models.CharField(
                choices=[
                    ("personal", "Personal"),
                    ("productos", "Productos"),
                    ("ventas", "Ventas"),
                    ("compras", "Compras"),
                    ("inventario", "Inventario"),
                ],
                max_length=20,
            ),
        ),
    ]
