# Generated by Django 5.2.14 on 2026-05-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('barbero', 'Barbero')], default='admin', max_length=20),
        ),
    ]
